const {Router} = require('express')
const {Index,AddInstitutions,CreateSubscription,getCallbackData,Get_Subscription_Fees,Post_Subscription_Fees,ActivateSubscriptions,SuspendSubscriptions,getAllSubscriptions,CreateCoupon,getCoupons,SuspendCoupon} = require("../Controllers/InstitutionController")
const InstitutionRouter = Router()
InstitutionRouter.get("/Institutions",Index)
.post("/Institution/Post",AddInstitutions)
.post("/Subscribe",CreateSubscription)
.post("/AddCoupon",CreateCoupon)
.get("/AllCoupons",getCoupons)
.post("/Suspend-Coupon",SuspendCoupon)
.post('/Callback-Data-For-Backend',getCallbackData)
.get('/All-Subscriptions',getAllSubscriptions)
.post('/Activate-Subscriptions',ActivateSubscriptions)
.post('/Suspend-Subscriptions',SuspendSubscriptions)
.get('/get-subscription-fees',Get_Subscription_Fees)
.post('/subscription-fees',Post_Subscription_Fees)
module.exports = InstitutionRouter