const {Router} = require('express')
const {Index,getPolls,LeadersPosts,getPosts,getInstitutionPolls,getInstitutionPosts,deletePolls,getPastPolls,getVotes,startPoll,stopPoll,RecordVote,getActivePolls,getActivePollVotes,getAllActivePolls,VOTE} = require('../Controllers/PollsController')
const PollsRouter = Router()
//set up the index route
PollsRouter.get("/Polls",Index)
.post("/Polls/Post",getPolls)
.post("/Leaders/Posts",LeadersPosts)
.get("/Leaders",getPosts)
.post("/Institution-Posts",getInstitutionPosts)
.post("/deletePolls",deletePolls)
.post("/startPolls",startPoll)
.post("/stopPolls",stopPoll)
.post('/ActivePolls',getActivePolls)
.post('/ActivePollVotes',getActivePollVotes)
.get('/Get-All-Active-Polls',getAllActivePolls)
.post("/Vote-A-Candidate",VOTE)
.post('/Record-A-Vote',RecordVote)
.post('/Get-All-Votes',getVotes)
.post("/Get-Past-Poll",getPastPolls)
.post('/Get-Institution-Polls',getInstitutionPolls)
module.exports = PollsRouter